version: "3.1"

services:
  app:
    build: .
    container_name: micro-auth-app
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=micro_auth
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./themes/microauth:/opt/jboss/keycloak/themes/microauth
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: micro-auth-db
    restart: always
    tty: true
    ports:
      - 33306:3306
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=micro_auth
      - MYSQL_ROOT_PASSWORD=root
